name: MediaRecorder test
on:
  push:
    branches: [master]
  schedule:
    # schedule to run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  parallel-tests:
    name: ${{ matrix.browser }} ${{ matrix.browser-version }} test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - browser: firefox
            version: latest
            os: ubuntu-latest

          - browser: chrome
            version: stable
            os: ubuntu-latest

          - browser: edge
            version: stable
            os: macos-latest  # todo: check setup-edge, broken on ubuntu

          - browser: safari
            version: stable
            os: macos-latest

    steps:
      - if: ${{ matrix.browser == 'firefox' }}
        id: setup-firefox
        name: Set up Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.version }}

      - if: ${{ matrix.browser == 'chrome' }}
        id: setup-chrome
        name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: ${{ matrix.version }}
          install-dependencies: true

      - if: ${{ matrix.browser == 'edge' }}
        id: setup-edge
        name: Set up Edge
        uses: browser-actions/setup-edge@v1
        with:
          edge-version: ${{ matrix.version }}

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # - name: Fix paths
      #   run: |
      #     if [[ -n "${{ steps.setup-chrome.outputs.chrome-path }}" ]]; then
      #       echo "${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_PATH;
      #     fi

      - name: Run tests
        id: run-tests
        run: |
          pip install -q 'selenium==4.*'
          echo "Running..."
          python run-tests.py
          echo "Done"

          cat info.txt >> "$GITHUB_OUTPUT"
          echo ""
          cat info.txt
          echo ""
          cat output.json
        env:
          BROWSER: ${{ matrix.browser }}
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.run-tests.outputs.browser-name }}-${{ steps.run-tests.outputs.browser-version }}-data
          path: output.json
          retention-days: 1

  aggregate-results:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: parallel-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/download-artifact@v4
        with:
          pattern: '*-data'
          path: dist/

      - name: Process test results
        run: |
          python compile-results.py

      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - uses: actions/deploy-pages@v4
        id: deployment
