name: MediaRecorder test

on:
  push:
    branches: [master]

jobs:
  parallel-tests:
    name: ${{ matrix.browser }} ${{ matrix.browser-version }} test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - browser: firefox
            version: latest
            os: ubuntu-latest

          - browser: chrome
            version: stable
            os: ubuntu-latest

          - browser: edge
            version: stable
            os: ubuntu-latest

          - browser: safari
            version: stable
            os: macos-latest

    steps:
      - if: ${{ matrix.browser == 'firefox' }}
        id: setup-firefox
        name: Set up Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.version }}

      - if: ${{ matrix.browser == 'chrome' }}
        id: setup-chrome
        name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: ${{ matrix.version }}
          install-dependencies: true

      - if: ${{ matrix.browser == 'edge' }}
        id: setup-edge
        name: Set up Edge
        uses: browser-actions/setup-edge@v1
        with:
          edge-version: ${{ matrix.version }}

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # - name: Fix paths
      #   run: |
      #     if [[ -n "${{ steps.setup-chrome.outputs.chrome-path }}" ]]; then
      #       echo "${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_PATH;
      #     fi

      - name: Run tests
        id: run-test
        run: |
          pip install -q 'selenium==4.*'
          echo "Running..."
          python run.py
          echo "Done"

          cat info.txt >> "$GITHUB_OUTPUT"
          echo ""
          cat info.txt
          echo ""
          cat output.json
        env:
          BROWSER: ${{ matrix.browser }}
        shell: bash

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.run-test.outputs.browser-name }}-${{ steps.run-test.outputs.browser-version }}-data
          path: output.json
          retention-days: 7
